# Generated by Django 4.1.7 on 2023-03-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=20, verbose_name='Название поля 1')),
                ('date', models.DateField(verbose_name='Дата 1')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время 1')),
                ('checkbox', models.BooleanField(verbose_name='Чек бокс 1')),
                ('integer', models.IntegerField(verbose_name='Число 1')),
                ('choices', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], verbose_name='Выборка')),
            ],
        ),
    ]
